@startuml
actor Estudiante
boundary "SoporteTecnicoView" as View
control "SoporteController" as Controller
entity "MensajeSoporte" as Mensaje
database "SoporteRepository" as Repository

== Flujo principal ==
Estudiante -> View --++: Acceder a la sección de soporte técnico
View -> Controller --++: Solicitar formulario de contacto
Controller -> View --++: Mostrar formulario de contacto
View -> Controller --++: Enviar mensaje de soporte
Controller -> Mensaje --++: Validar mensaje
Mensaje -> Controller --++: Mensaje válido
Controller -> Repository --++: Registrar mensaje de soporte
Repository -> Controller --++: Confirmación de registro
Controller -> View --++: Confirmación de mensaje enviado

== Flujo alternativo ==

alt [Error Error técnico al enviar el mensaje]
    Controller -> View --++: Mostrar mensaje de error
end
@enduml