@startuml
actor Estudiante
boundary "PostulacionTutorView" as View
control "PostulacionController" as Controller
entity "Postulacion" as Postulacion
database "PostulacionesRepository" as Repository

== Flujo principal ==
Estudiante -> View --++: Acceder a la función de postulación a tutor
View -> Controller --++: Solicitar formulario de postulación
Controller -> View --++: Mostrar formulario de postulación
View -> Controller --++: Enviar datos de la postulación
Controller -> Postulacion --++: Validar información
Postulacion -> Controller --++: Información válida
Controller -> Repository --++: Registrar postulación
Repository -> Controller --++: Confirmación de registro
Controller -> View --++: Confirmación de postulación enviada
@enduml