@startuml
actor Administrador
boundary "CrearProfesorView" as View
control "ProfesoresController" as Controller
entity "Profesor" as Model
database "ProfesoresRepository" as Repository

== Flujo principal ==
Administrador -> View --++: Acceder a la sección de alta de profesor
View -> Controller --++: Solicitar formulario de alta de profesor
Controller -> View --++: Mostrar formulario de alta de profesor
View -> Controller --++: Enviar formulario completo
Controller -> Model --++: Validar información
Model -> Controller --++: Información válida
Controller -> Repository --++: Registrar nuevo profesor
Repository -> Controller --++: Confirmación de registro
Controller -> View --++: Confirmación de alta realizada

== Flujo alternativo ==
alt [D Documentos cargados no son válidos o están incompletos]
    Model -> Controller --++: Información no válida
    Controller -> View --++: Mostrar mensaje de error y solicitar recarga de documentos
end
@enduml
