@startuml
actor Estudiante
boundary "ComunidadView" as View
control "ComunidadController" as Controller
entity "Posteo" as Post
database "PosteosRepository" as Repository

== Flujo principal ==
Estudiante -> View --++: Acceder a la sección de comunidad
View -> Controller --++: Solicitar formulario de creación de posteo
Controller -> View --++: Mostrar formulario de creación de posteo
View -> Controller --++: Enviar datos del posteo
Controller -> Post --++: Validar contenido del posteo
Post -> Controller --++: Contenido válido
Controller -> Repository --++: Registrar nuevo posteo
Repository -> Controller --++: Confirmación de registro
Controller -> View --++: Confirmación de creación del posteo


== Flujo alternativo ==

alt [Conte Contenido del posteo excede el límite de caracteres permitidos]
    Post -> Controller --++: Contenido no válido
    Controller -> View --++: Mostrar mensaje de error
end
@enduml