@startuml
actor Administrador
boundary "ComunidadView" as View
control "PosteosController" as Controller
entity "Posteo" as Model
database "PosteosRepository" as Repository

== Flujo principal ==
Administrador -> View : Acceder a la comunidad general de EduMatch
activate View
View -> Controller : Cargar actividad planificada
activate Controller
Controller -> View : Mostrar formulario de carga de actividad
View -> Controller : Enviar datos de la actividad
Controller -> Model : Crear nueva actividad con datos
activate Model
Model --> Controller : Confirmación de creación de actividad
deactivate Model
Controller -> Repository : Guardar nueva actividad en el repositorio
activate Repository
Repository --> Controller : Confirmación de guardado
deactivate Repository
Controller -> View : Mostrar mensaje de actividad generada con éxito
deactivate Controller
deactivate View

@enduml
