@startuml
actor Administrador
boundary "EliminarProfesorView" as View
control "ProfesoresController" as Controller
database "ProfesoresRepository" as Repository

== Flujo principal ==
Administrador -> View --++: Acceder a la sección de eliminación de profesor
View -> Controller --++: Solicitar lista de profesores
Controller -> Repository --++: Obtener lista de profesores
Repository -> Controller --++: Enviar lista de profesores
Controller -> View --++: Mostrar lista de profesores
View -> Controller --++: Solicitar confirmación de eliminación
Controller -> View --++: Mostrar ventana de confirmación
View -> Controller --++: Enviar confirmación
Controller -> Repository --++: Eliminar información del profesor
Repository -> Controller --++: Confirmación de eliminación
Controller -> View --++: Confirmación de eliminación realizada

== Flujo alternativo ==
alt [A Administrador decide cancelar la eliminación]
    Administrador -> View --++: Cancelar eliminación
    View -> Controller --++: Solicitar cancelación
    Controller -> View --++: Confirmación de cancelación
end
@enduml
